version: "3"
services:
  link_api_test:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: link_api_test
    ports: 
      - "3000:3000"
    
    command: ["node", "src/server.js"]
    restart: on-failure
